package com.ifisolution.swbackend.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * AnswerMst generated by hbm2java
 */
@Entity
@Table(name = "answer_mst")
public class AnswerMst implements java.io.Serializable {

	private Integer answerId;
	private QuestionMst questionMst;
	private String answerContent;

	public AnswerMst() {
	}

	public AnswerMst(QuestionMst questionMst, String answerContent) {
		this.questionMst = questionMst;
		this.answerContent = answerContent;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "answer_id", unique = true, nullable = false)
	public Integer getAnswerId() {
		return this.answerId;
	}

	public void setAnswerId(Integer answerId) {
		this.answerId = answerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "question_id")
	@JsonIgnore
	public QuestionMst getQuestionMst() {
		return this.questionMst;
	}

	public void setQuestionMst(QuestionMst questionMst) {
		this.questionMst = questionMst;
	}

	@Column(name = "answer_content")
	public String getAnswerContent() {
		return this.answerContent;
	}

	public void setAnswerContent(String answerContent) {
		this.answerContent = answerContent;
	}

}
