package com.ifisolution.swbackend.model;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * DocumentMst generated by hbm2java
 */
@Entity
@Table(name = "document_mst", catalog = "swbackend")
public class DocumentMst implements java.io.Serializable {

	private Integer docId;
	private String docName;
	private String docType;
	private String docPath;
	private String createBy;
	private String updateBy;
	private Date createTime;
	private Date updateTime;
	private String description;
	private String status;
	private Set<RequestMst> requestMsts = new HashSet<RequestMst>(0);

	public DocumentMst() {
	}

	public DocumentMst(String docName, String docType, String docPath, String createBy, String updateBy,
			Date createTime, Date updateTime, String description, String status, Set<RequestMst> requestMsts) {
		this.docName = docName;
		this.docType = docType;
		this.docPath = docPath;
		this.createBy = createBy;
		this.updateBy = updateBy;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.description = description;
		this.status = status;
		this.requestMsts = requestMsts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "doc_id", unique = true, nullable = false)
	public Integer getDocId() {
		return this.docId;
	}

	public void setDocId(Integer docId) {
		this.docId = docId;
	}

	@Column(name = "doc_name", length = 45)
	public String getDocName() {
		return this.docName;
	}

	public void setDocName(String docName) {
		this.docName = docName;
	}

	@Column(name = "doc_type", length = 45)
	public String getDocType() {
		return this.docType;
	}

	public void setDocType(String docType) {
		this.docType = docType;
	}

	@Column(name = "doc_path", length = 45)
	public String getDocPath() {
		return this.docPath;
	}

	public void setDocPath(String docPath) {
		this.docPath = docPath;
	}

	@Column(name = "create_by", length = 45)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Column(name = "update_by", length = 45)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_time", length = 10)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "update_time", length = 10)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "status", length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "documentMsts")
	@JsonIgnore
	public Set<RequestMst> getRequestMsts() {
		return this.requestMsts;
	}

	public void setRequestMsts(Set<RequestMst> requestMsts) {
		this.requestMsts = requestMsts;
	}

}
