package com.ifisolution.swbackend.model;

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NotificationMst generated by hbm2java
 */
@Entity
@Table(name = "notification_mst", catalog = "swbackend")
public class NotificationMst implements java.io.Serializable {

	private NotificationMstId id;
	private RequestMst requestMst;
	private String productor;
	private String message;
	private String actionCode;
	private Date date;

	public NotificationMst() {
	}

	public NotificationMst(NotificationMstId id, RequestMst requestMst) {
		this.id = id;
		this.requestMst = requestMst;
	}

	public NotificationMst(NotificationMstId id, RequestMst requestMst, String productor, String message,
			String actionCode, Date date) {
		this.id = id;
		this.requestMst = requestMst;
		this.productor = productor;
		this.message = message;
		this.actionCode = actionCode;
		this.date = date;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idNotification", column = @Column(name = "id_notification", nullable = false)),
			@AttributeOverride(name = "idRequest", column = @Column(name = "id_request", nullable = false)) })
	public NotificationMstId getId() {
		return this.id;
	}

	public void setId(NotificationMstId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_request", nullable = false, insertable = false, updatable = false)
	public RequestMst getRequestMst() {
		return this.requestMst;
	}

	public void setRequestMst(RequestMst requestMst) {
		this.requestMst = requestMst;
	}

	@Column(name = "productor", length = 45)
	public String getProductor() {
		return this.productor;
	}

	public void setProductor(String productor) {
		this.productor = productor;
	}

	@Column(name = "message", length = 45)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Column(name = "action_code", length = 45)
	public String getActionCode() {
		return this.actionCode;
	}

	public void setActionCode(String actionCode) {
		this.actionCode = actionCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
