package com.ifisolution.swbackend.model;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NotificationMstId generated by hbm2java
 */
@Embeddable
public class NotificationMstId implements java.io.Serializable {

	private int idNotification;
	private int idRequest;

	public NotificationMstId() {
	}

	public NotificationMstId(int idNotification, int idRequest) {
		this.idNotification = idNotification;
		this.idRequest = idRequest;
	}

	@Column(name = "id_notification", nullable = false)
	public int getIdNotification() {
		return this.idNotification;
	}

	public void setIdNotification(int idNotification) {
		this.idNotification = idNotification;
	}

	@Column(name = "id_request", nullable = false)
	public int getIdRequest() {
		return this.idRequest;
	}

	public void setIdRequest(int idRequest) {
		this.idRequest = idRequest;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NotificationMstId))
			return false;
		NotificationMstId castOther = (NotificationMstId) other;

		return (this.getIdNotification() == castOther.getIdNotification())
				&& (this.getIdRequest() == castOther.getIdRequest());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdNotification();
		result = 37 * result + this.getIdRequest();
		return result;
	}

}
