//package com.ifisolution.swbackend.model;
//
//import javax.persistence.Column;
//import javax.persistence.Entity;
//import javax.persistence.FetchType;
//import javax.persistence.GeneratedValue;
//import javax.persistence.Id;
//import javax.persistence.JoinColumn;
//import javax.persistence.ManyToOne;
//import javax.persistence.OneToOne;
//import javax.persistence.PrimaryKeyJoinColumn;
//import javax.persistence.Table;
//import org.hibernate.annotations.GenericGenerator;
//import org.hibernate.annotations.Parameter;
//
///**
// * QuestionSubMst generated by hbm2java
// */
//@Entity
//@Table(name = "question_sub_mst", catalog = "swbackend")
//public class QuestionSubMst implements java.io.Serializable {
//
//	private int questionSubId;
//	private QuestionMst questionMstByQuestionId;
//	private QuestionMst questionMstByQuestionId_1;
//
//	public QuestionSubMst() {
//	}
//
//	public QuestionSubMst(QuestionMst questionMstByQuestionId, QuestionMst questionMstByQuestionId_1) {
//		this.questionMstByQuestionId = questionMstByQuestionId;
//		this.questionMstByQuestionId_1 = questionMstByQuestionId_1;
//	}
//
//	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "questionMstByQuestionId"))
//	@Id
//	@GeneratedValue(generator = "generator")
//
//	@Column(name = "question_sub_id", unique = true, nullable = false)
//	public int getQuestionSubId() {
//		return this.questionSubId;
//	}
//
//	public void setQuestionSubId(int questionSubId) {
//		this.questionSubId = questionSubId;
//	}
//
//	@OneToOne(fetch = FetchType.LAZY)
//	@PrimaryKeyJoinColumn
//	public QuestionMst getQuestionMstByQuestionId() {
//		return this.questionMstByQuestionId;
//	}
//
//	public void setQuestionMstByQuestionId(QuestionMst questionMstByQuestionId) {
//		this.questionMstByQuestionId = questionMstByQuestionId;
//	}
//
//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "question_id", nullable = false)
//	public QuestionMst getQuestionMstByQuestionId_1() {
//		return this.questionMstByQuestionId_1;
//	}
//
//	public void setQuestionMstByQuestionId_1(QuestionMst questionMstByQuestionId_1) {
//		this.questionMstByQuestionId_1 = questionMstByQuestionId_1;
//	}
//
//}
