package com.ifisolution.swbackend.model;
// Generated Jan 2, 2018 6:00:06 PM by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RequestQuestionMstId generated by hbm2java
 */
@Embeddable
public class RequestQuestionMstId implements java.io.Serializable {

	private int requestId;
	private int questionId;

	public RequestQuestionMstId() {
	}

	public RequestQuestionMstId(int requestId, int questionId) {
		this.requestId = requestId;
		this.questionId = questionId;
	}

	@Column(name = "request_id", nullable = false)
	public int getRequestId() {
		return this.requestId;
	}

	public void setRequestId(int requestId) {
		this.requestId = requestId;
	}

	@Column(name = "question_id", nullable = false)
	public int getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(int questionId) {
		this.questionId = questionId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RequestQuestionMstId))
			return false;
		RequestQuestionMstId castOther = (RequestQuestionMstId) other;

		return (this.getRequestId() == castOther.getRequestId()) && (this.getQuestionId() == castOther.getQuestionId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRequestId();
		result = 37 * result + this.getQuestionId();
		return result;
	}

}
