package com.ifisolution.swbackend.model;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * UserMst generated by hbm2java
 */
@Entity
@Table(name = "user_mst", catalog = "swbackend")
public class UserMst implements java.io.Serializable {

	private Integer userId;
	private String userName;
	private String email;
	private String address;
	private Integer roleId;
	private String password;
	private Set<RequestMst> requestMsts = new HashSet<RequestMst>(0);

	public UserMst() {
	}

	public UserMst(String userName, String email, String address, Integer roleId, String password,
			Set<RequestMst> requestMsts) {
		this.userName = userName;
		this.email = email;
		this.address = address;
		this.roleId = roleId;
		this.password = password;
		this.requestMsts = requestMsts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "user_id", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "user_name", length = 45)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "address", length = 45)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "role_id")
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Column(name = "password", length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userMst")
	@JsonIgnore
	public Set<RequestMst> getRequestMsts() {
		return this.requestMsts;
	}

	public void setRequestMsts(Set<RequestMst> requestMsts) {
		this.requestMsts = requestMsts;
	}

}
